# Generated by Django 5.0.1 on 2024-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAVApp', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMore',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.CharField(max_length=255)),
                ('defination', models.CharField(max_length=255)),
                ('timeComplexity', models.CharField(max_length=255)),
                ('spaceComplexity', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
